name: 'Move labeled or milestoned pull request to a specific project column'
description: 'Move pull request that has been labeled or milestoned to a specific column in a project'
branding:
  icon: 'move'
  color: 'green'
inputs:
  action-token:
    description: 'Token for the repo. The usual secrets.GITHUB_TOKEN will not be sufficient, you must create a token that has repo permissions'
    required: true
  project-url:
    description: 'The url of the project'
    required: true
  column-name:
    description: 'The column that the card should end up'
    required: false
  label-name:
    description: 'The label that specifies if an pull request should be automatically moved to the column (mutually exclusive with milestone-name). Use `*` to use it with any label'
    required: false
  milestone-name:
    description: 'The milestone that specifies if an pull request should be automatically moved to the column (mutually exclusive with label-name)'
    required: false
  delete-card:
    description: '"true" if you want to delete the card from the project'
    required: false
  columns-to-ignore:
    description: 'Comma separated list of columns to ignore. If a card/pull request is already in one of these columns, it will not be moved. Use `*` to ignore all columns'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
